version: '3.3'

services:

    nginx:
        container_name: nginx
        build: ./requirements/nginx
        restart: always
        ports:
            - "443:443"
        links:
            - wordpress
        volumes:
            - ./tools/code:/code

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        restart: always
        volumes:
            - ./tools/code:/code

#    mariadb:
#        container_name: mariadb
#        build: ./requirements/mariadb
#        restart: always
#        ports:
#            - "3306:3306"
