version: '3.3'

services:
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        restart: always
        networks:
            - network
        volumes:
            - ./tools/code:/code
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        restart: always
        networks:
            - network
        ports:
            - "443:443"
        volumes:
            - ./tools/code:/code
        depends_on:
            - wordpress

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: always
        ports:
            - "3306:3306"

networks:
    network:
