version: '3.3'
services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - network
    volumes:
      - type: volume
        source: website
        target: /code
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_CLIENT=${DB_CLIENT}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - network
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    networks:
      - network
    volumes:
      - type: volume
        source: website
        target: /code
volumes:
  website:
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/srcs/requirements/tools/code"
  database:
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/srcs/requirements/tools/db"
networks:
  network:
