version: '3.4'
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_CLIENT=${DB_CLIENT}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - network
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TITLE=${TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
    networks:
      - network
    volumes:
      - type: volume
        source: website
        target: /var/www/html
  nginx:
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - network
    volumes:
      - type: volume
        source: website
        target: /var/www/html
volumes:
  website:
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/website"
  database:
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/database"
networks:
  network:
